// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjfbgekgfqjkeiyejmbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqZmJnZWtnZnFqa2VpeWVqbWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjYyOTAsImV4cCI6MjA2NTA0MjI5MH0.sR2pVX4-QC0Mbxm13nmMdN31LpBCTJPUO5dF5OpiuKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});